In [26]:
import numpy as np
import matplotlib.pyplot as plt


In [27]:
N = 2
L = 100     #bok siatki
a = L/(2*N)     #bok kwadratowego elementu




In [123]:
Net = np.zeros([2*N+1, 2*N+1])      #sieć węzłów
# Net[-1, 0] = 1

Net_first = np.linspace(1, 2*N+1, 2*N+1)    

# elements = np.zeros(2*N)

In [134]:
for i in range(0, 2*N+1):
    for j in range(0, 2*N+1):
        Net[i, j] = Net_first[j] + (2*N+1)*i

Net = Net[::-1]



In [135]:
print(Net)
# print(Net_1)

[[21. 22. 23. 24. 25.]
 [16. 17. 18. 19. 20.]
 [11. 12. 13. 14. 15.]
 [ 6.  7.  8.  9. 10.]
 [ 1.  2.  3.  4.  5.]]


In [132]:
elements = np.zeros([2*N, 2*N])

for i in range(0, 2*N):
    for j in range(0, 2*N):
        elements[i, j] = Net_first[j] + 2*N*i

elements = elements[::-1]

In [133]:
print(elements)

[[13. 14. 15. 16.]
 [ 9. 10. 11. 12.]
 [ 5.  6.  7.  8.]
 [ 1.  2.  3.  4.]]


In [137]:
knots = np.zeros([2, 2])
print(knots)

[[0. 0.]
 [0. 0.]]


In [139]:
if knots[0, 0]:
    local_num = 3
elif knots[0, 1]:
    local_num = 4
elif knots[1, 0]:
    local_num = 1
elif knots[1, 1]:
    local_num = 2
        

In [153]:
Big_net = np.zeros([2*N+1, 2*N+1])
Bnet_reference = np.linspace(-L/2.0, L/2.0, 2*N+1)    
print(Bnet_reference)

[-50. -25.   0.  25.  50.]
